language: go

go:
  - 1.7

go_import_path: github.com/centurylinkcloud/clc-go-cli

before_install:
  - go get github.com/tools/godep
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/mattn/goveralls

install:
  - godep restore

script:
    - $HOME/gopath/bin/goveralls -service=travis-ci